
FROM python:3.10

RUN pip install chocolate_app

RUN apt-get update && apt-get install -y nvidia-driver-525
RUN reboot

RUN apt-get install -y nvidia-cuda-toolkit
RUN mkdir ~/nvidia/ && cd ~/nvidia/
RUN git clone https://git.videolan.org/git/ffmpeg/nv-codec-headers.git
RUN cd nv-codec-headers && make install
RUN apt-get install -y build-essential yasm cmake libtool libc6 libc6-dev unrar-free unzip wget libnuma1 libnuma-dev

RUN cd ~/nvidia/
RUN git clone https://git.ffmpeg.org/ffmpeg.git ffmpeg/

RUN cd ~/nvidia/ffmpeg/
RUN ./configure --enable-nonfree --enable-cuda-nvcc --enable-libnpp --extra-cflags=-I/usr/local/cuda/include --extra-ldflags=-L/usr/local/cuda/lib64

RUN make -j $(nproc)

RUN make install

EXPOSE 8888

RUN echo 'export PATH=$PATH:/usr/local/bin' >> ~/.bashrc

CMD ["chocolate_app"]